name: build-and-test

on : [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    # Set up Java 17
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64

    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE

    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      run: ./gradlew build